Copy files out and re-use them.

diff --git a/test/run b/test/run
--- a/test/run
+++ b/test/run
@@ -8,8 +8,14 @@ tag=docker-compilation-images-hello-world
 dir=$(cd $(dirname $0)/.. && pwd)
 cd $dir
 
-set -x
-
 ./docker-build --tag=run:$tag test/hello-world
-output=$(docker run --rm -it $tag)
-[[ $output == 'Hello, world!' ]]
+expected=$(echo -e 'Hello, world!\r\n')
+actual=$(docker run --rm --interactive --tty $tag)
+echo
+[[ $expected == $actual ]] && echo 'Test passed.' || {
+    echo 'Test failed.'
+    echo 'Expected output:'
+    hexdump -C <<< $expected
+    echo 'Actual output:'
+    hexdump -C <<< $actual
+}
